### ISSUE TITLE
Commercial use of Maze generator puzzles

### ISSUE THREAD

**Issue by Atiqa4004** [busyDuckman/MazeMaker#2]
Hello
I am a graphic designer. I am designing an activity and colouring book for kids to sell a paperback version of my book via online store. Can i use your free services of maze generator? Can I use this tool for free? Can I use the tool and earn money from my book by publishing those maze sheets in my book?
Please guide me

Thank you

**Comment by busyDuckman** [comment]
Hi, I am glad to see the software being used in publication.

Can I use your free services of maze generator? **Yes**
Can I use this tool for free? **Yes**
Can I use the tool and earn money from my book by publishing those maze sheets in my book? **Yes**

This software is provided free to use for all commercial / non-commercial / educational, puzzle publication purposes.

I really appreciate it if you mention this project in the book somewhere - though that is not required.
More info on terms is on the web page: http://busyducks.com/wp_4_1/2015/07/03/maze-software/

Good luck with your project :)

**Comment by Atiqa4004** [comment]
Hello
I have a question related to maze maker. If I make puzzles/maze with this
software, do you allow that maze to see publically? Or just give access to
only particular person who is interested in getting desired maze. Can I
hold copyrights of puzzles generated by me by using your free software??

Also tell me if you have other software like word search puzzles, worksheet
maker or much more. If you have some sister sites of other puzzles maker
software.
Waiting to hear from you soon.
Thank you so much

**Comment by busyDuckman** [comment]
Hi, 

> I have a question related to maze maker. If I make puzzles/maze with this
> software, do you allow that maze to see publically? Or just give access to
> only particular person who is interested in getting desired maze

You can treat the software like any other design software, its output is an image you can share with whoever you want.

> Can I hold copyrights of puzzles generated by me by using your free software??

I am not sure, I am no expert in copyright law. I would think the direct output form the software requires no skill, therefore would not constitute an "original work of authorship”. However if you created a derivative work, by adding some artwork for example,  then you would probably have a picture you could copyright. Again I am no lawyer, this is not legal advice.

> Also tell me if you have other software like word search puzzles, worksheet
> maker or much more. If you have some sister sites of other puzzles maker
> software.

I have some crossword software, its not very polished and the link is down at the moment. As you have jogged my memory, I will move it to git hub under an open licence soon.
http://busyducks.com/wp_4_1/2015/06/20/crossword-software-alpha/

**Comment by Atiqa4004** [comment]
Hello
Please complete you cross word software. I want to use this software.

**Comment by TCulture** [comment]
Hello,
I would like to know if the Maze Generator software is still free to use for commercial purposes. I would like to create some for making puzzle books.
